/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_walterreyes;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author hp
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        JR_Ingeniería = new javax.swing.JRadioButton();
        JR_Licenciaturas = new javax.swing.JRadioButton();
        JR_Salúd = new javax.swing.JRadioButton();
        cb_Ingeniería = new javax.swing.JComboBox<>();
        cb_Licenciaturas = new javax.swing.JComboBox<>();
        cb_Salúd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Costo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jefe = new javax.swing.JTextField();
        Guardar_Carreras = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Editar_Carrera = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jDialog2 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Numero_Cuenta = new javax.swing.JTextField();
        SP_Edad = new javax.swing.JSpinner();
        Botón_M = new javax.swing.JRadioButton();
        Botón_F = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cb_Carreras = new javax.swing.JComboBox<>();
        Agregar_Alumnos = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Editar_Estudiante = new javax.swing.JPopupMenu();
        Editar_Estudiantes = new javax.swing.JMenuItem();
        Eliminar_Estudiantes = new javax.swing.JMenuItem();
        Agregar_al_arbol = new javax.swing.JMenuItem();
        jDialog3 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Clase = new javax.swing.JTextField();
        Sección = new javax.swing.JTextField();
        Edificio = new javax.swing.JTextField();
        RB_Sí = new javax.swing.JRadioButton();
        RB_No = new javax.swing.JRadioButton();
        Botón_crearclase = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Salón = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Editar_Clase = new javax.swing.JPopupMenu();
        Editar_clase1 = new javax.swing.JMenuItem();
        Eliminar_Clase = new javax.swing.JMenuItem();
        jDialog4 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Apellido_M = new javax.swing.JTextField();
        Nombre_M1 = new javax.swing.JTextField();
        Salario_M = new javax.swing.JTextField();
        cb_clases_M = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        Edad_M = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Editar_Maestros = new javax.swing.JPopupMenu();
        Editar_maestro = new javax.swing.JMenuItem();
        Eliminar_Maestro = new javax.swing.JMenuItem();
        jDialog5 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Apellido_M1 = new javax.swing.JTextField();
        Nombre_M2 = new javax.swing.JTextField();
        Salario_M1 = new javax.swing.JTextField();
        cb_clases_M1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Edad_M1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jDialog6 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        JR_Ingeniería1 = new javax.swing.JRadioButton();
        JR_Licenciaturas1 = new javax.swing.JRadioButton();
        JR_Salúd1 = new javax.swing.JRadioButton();
        cb_Ingeniería1 = new javax.swing.JComboBox<>();
        cb_Licenciaturas1 = new javax.swing.JComboBox<>();
        cb_Salúd1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        Costo1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Jefe1 = new javax.swing.JTextField();
        Guardar_Carreras1 = new javax.swing.JButton();
        jDialog7 = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Clase1 = new javax.swing.JTextField();
        Sección1 = new javax.swing.JTextField();
        Edificio1 = new javax.swing.JTextField();
        RB_Sí1 = new javax.swing.JRadioButton();
        RB_No1 = new javax.swing.JRadioButton();
        Botón_crearclase1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        Salón1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Botón_Carrera = new javax.swing.JButton();
        Botón_Estudiantes = new javax.swing.JButton();
        Botón_Clase = new javax.swing.JButton();
        Botón_Maestros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Carrera = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Estudiantes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_Clases = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Maestros = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jDialog1.setTitle("AgrergarCarreras");

        buttonGroup1.add(JR_Ingeniería);
        JR_Ingeniería.setText("Facultad de Ingeniería");
        JR_Ingeniería.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_IngenieríaActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR_Licenciaturas);
        JR_Licenciaturas.setText("Licenciaturas");
        JR_Licenciaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_LicenciaturasActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR_Salúd);
        JR_Salúd.setText("Ciencias de la Salúd");
        JR_Salúd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_SalúdActionPerformed(evt);
            }
        });

        cb_Ingeniería.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería enSistemas computacionales", "Ingeniería Industrial y de sistemas ", "Ingeniería Mecatrónica", "Ingeniería Biomédica", "Ingeniería en Energía" }));

        cb_Licenciaturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciaturas en Finanzas", "licenciatura en Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia " }));
        cb_Licenciaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_LicenciaturasActionPerformed(evt);
            }
        });

        cb_Salúd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina y Cirujía", "Odontología", "Nutrición", "Terapia física y ocupacional" }));

        jLabel7.setText("Costo Mensual");

        jLabel8.setText("Jefe de Carrera");

        Guardar_Carreras.setText("Guardar");
        Guardar_Carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_CarrerasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JR_Ingeniería))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_Ingeniería, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JR_Licenciaturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JR_Salúd)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_Licenciaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cb_Salúd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar_Carreras)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Costo)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR_Ingeniería)
                    .addComponent(JR_Licenciaturas)
                    .addComponent(JR_Salúd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Ingeniería, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Licenciaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Salúd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Guardar_Carreras)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        Editar_Carrera.add(Editar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Editar_Carrera.add(Eliminar);

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel12.setText("Edad");

        jLabel13.setText("Genero");

        jLabel14.setText("Carrera");

        buttonGroup2.add(Botón_M);
        Botón_M.setText("M");

        buttonGroup2.add(Botón_F);
        Botón_F.setText("F");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SP_Edad)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numero_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(75, 75, 75)
                        .addComponent(Botón_M)
                        .addGap(18, 18, 18)
                        .addComponent(Botón_F)))
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Numero_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SP_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Botón_M)
                    .addComponent(Botón_F))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jLabel11.setText("Numero de cuenta");

        Agregar_Alumnos.setText("Agrergar");
        Agregar_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_AlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Agregar_Alumnos)
                            .addComponent(cb_Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog2Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 71, Short.MAX_VALUE)))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel11)
                .addGap(98, 98, 98)
                .addComponent(cb_Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(Agregar_Alumnos)
                .addGap(28, 28, 28))
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Editar_Estudiantes.setText("Editar");
        Editar_Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_EstudiantesActionPerformed(evt);
            }
        });
        Editar_Estudiante.add(Editar_Estudiantes);

        Eliminar_Estudiantes.setText("Eliminar");
        Eliminar_Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_EstudiantesActionPerformed(evt);
            }
        });
        Editar_Estudiante.add(Eliminar_Estudiantes);

        Agregar_al_arbol.setText("Agregar al Arbol");
        Agregar_al_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_al_arbolActionPerformed(evt);
            }
        });
        Editar_Estudiante.add(Agregar_al_arbol);

        jLabel15.setText("Clase");

        jLabel16.setText("Sección");

        jLabel17.setText("Edificio");

        jLabel18.setText("Aire");

        buttonGroup3.add(RB_Sí);
        RB_Sí.setText("Si");

        buttonGroup3.add(RB_No);
        RB_No.setText("No");

        Botón_crearclase.setText("Agregar");
        Botón_crearclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_crearclaseActionPerformed(evt);
            }
        });

        jLabel23.setText("Salón numero:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sección, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edificio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(36, 36, 36)
                        .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RB_Sí)
                        .addGap(31, 31, 31)
                        .addComponent(RB_No))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Botón_crearclase)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(Salón, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Salón, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(RB_Sí)
                    .addComponent(RB_No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botón_crearclase)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Editar_clase1.setText("Editar clase");
        Editar_clase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_clase1ActionPerformed(evt);
            }
        });
        Editar_Clase.add(Editar_clase1);

        Eliminar_Clase.setText("Eliminar Clase");
        Eliminar_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ClaseActionPerformed(evt);
            }
        });
        Editar_Clase.add(Eliminar_Clase);

        jLabel19.setText("Nombre");

        jLabel20.setText("Apellido");

        jLabel21.setText("Salario");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Edad");

        jLabel25.setText("Clases");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edad_M, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario_M, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido_M, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(cb_clases_M, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Nombre_M1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Apellido_M))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Salario_M))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Edad_M))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_clases_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
            .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel22.setText("Clase que imparte");

        Editar_maestro.setText("Editar_Maestro");
        Editar_maestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_maestroActionPerformed(evt);
            }
        });
        Editar_Maestros.add(Editar_maestro);

        Eliminar_Maestro.setText("Eliminar maestro");
        Eliminar_Maestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_MaestroActionPerformed(evt);
            }
        });
        Editar_Maestros.add(Eliminar_Maestro);

        jLabel26.setText("Nombre");

        jLabel27.setText("Apellido");

        jLabel28.setText("Salario");

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel29.setText("Edad");

        jLabel30.setText("Clases");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edad_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_M2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(cb_clases_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Nombre_M2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Apellido_M1))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Salario_M1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Edad_M1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_clases_M1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
            .addGroup(jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jDialog6.setTitle("AgrergarCarreras");

        buttonGroup1.add(JR_Ingeniería1);
        JR_Ingeniería1.setText("Facultad de Ingeniería");
        JR_Ingeniería1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_Ingeniería1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR_Licenciaturas1);
        JR_Licenciaturas1.setText("Licenciaturas");
        JR_Licenciaturas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_Licenciaturas1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JR_Salúd1);
        JR_Salúd1.setText("Ciencias de la Salúd");
        JR_Salúd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_Salúd1ActionPerformed(evt);
            }
        });

        cb_Ingeniería1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería enSistemas computacionales", "Ingeniería Industrial y de sistemas ", "Ingeniería Mecatrónica", "Ingeniería Biomédica", "Ingeniería en Energía" }));

        cb_Licenciaturas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciaturas en Finanzas", "licenciatura en Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia " }));
        cb_Licenciaturas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_Licenciaturas1ActionPerformed(evt);
            }
        });

        cb_Salúd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina y Cirujía", "Odontología", "Nutrición", "Terapia física y ocupacional" }));

        jLabel31.setText("Costo Mensual");

        jLabel32.setText("Jefe de Carrera");

        Guardar_Carreras1.setText("Guardar");
        Guardar_Carreras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_Carreras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JR_Ingeniería1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_Ingeniería1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(JR_Licenciaturas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JR_Salúd1)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cb_Licenciaturas1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(cb_Salúd1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar_Carreras1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Jefe1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Costo1)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR_Ingeniería1)
                    .addComponent(JR_Licenciaturas1)
                    .addComponent(JR_Salúd1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Ingeniería1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Licenciaturas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Salúd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(Costo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(Jefe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Guardar_Carreras1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel33.setText("Clase");

        jLabel34.setText("Sección");

        jLabel35.setText("Edificio");

        jLabel36.setText("Aire");

        buttonGroup3.add(RB_Sí1);
        RB_Sí1.setText("Si");

        buttonGroup3.add(RB_No1);
        RB_No1.setText("No");

        Botón_crearclase1.setText("Agregar");
        Botón_crearclase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_crearclase1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Salón numero:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sección1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edificio1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(36, 36, 36)
                        .addComponent(Clase1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RB_Sí1)
                        .addGap(31, 31, 31)
                        .addComponent(RB_No1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Botón_crearclase1)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(Salón1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Clase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sección1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(Edificio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(Salón1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(RB_Sí1)
                    .addComponent(RB_No1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botón_crearclase1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jDialog7Layout = new javax.swing.GroupLayout(jDialog7.getContentPane());
        jDialog7.getContentPane().setLayout(jDialog7Layout);
        jDialog7Layout.setHorizontalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog7Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jDialog7Layout.setVerticalGroup(
            jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(jDialog7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 48)); // NOI18N
        jLabel1.setText("UNITEC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 11, 149, -1));

        Botón_Carrera.setText("Agregar Carrera");
        Botón_Carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_CarreraActionPerformed(evt);
            }
        });
        getContentPane().add(Botón_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        Botón_Estudiantes.setText("Agregar Estudiantes");
        Botón_Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_EstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(Botón_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, -1, -1));

        Botón_Clase.setText("Agregar Clase");
        Botón_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_ClaseActionPerformed(evt);
            }
        });
        getContentPane().add(Botón_Clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        Botón_Maestros.setText("Agregar Maestro");
        Botón_Maestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_MaestrosActionPerformed(evt);
            }
        });
        getContentPane().add(Botón_Maestros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, -1, -1));

        jLabel2.setText("Carrera");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 91, -1, -1));

        jLabel3.setText("Estudiante");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 91, -1, -1));

        jLabel4.setText("Clases");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 51, -1));

        jLabel5.setText("Maestros");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 51, -1));

        JL_Carrera.setModel(new DefaultListModel());
        JL_Carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_CarreraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JL_Carrera);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 302, -1));

        JL_Estudiantes.setModel(new DefaultListModel());
        JL_Estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_EstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JL_Estudiantes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 116, 341, -1));

        JL_Clases.setModel(new DefaultListModel());
        JL_Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_ClasesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JL_Clases);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 360, -1));

        JL_Maestros.setModel(new DefaultListModel());
        JL_Maestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_MaestrosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JL_Maestros);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 360, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Arbol");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 61, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jTree1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 210, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botón_CarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_CarreraActionPerformed
        jDialog1.setModal(true);
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);


    }//GEN-LAST:event_Botón_CarreraActionPerformed

    private void JR_IngenieríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_IngenieríaActionPerformed
        cb_Licenciaturas.setVisible(false);
        cb_Salúd.setVisible(false);
        cb_Ingeniería.setVisible(true);
    }//GEN-LAST:event_JR_IngenieríaActionPerformed

    private void cb_LicenciaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_LicenciaturasActionPerformed

    }//GEN-LAST:event_cb_LicenciaturasActionPerformed

    private void JR_SalúdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_SalúdActionPerformed
        cb_Licenciaturas.setVisible(false);
        cb_Salúd.setVisible(true);
        cb_Ingeniería.setVisible(false);
    }//GEN-LAST:event_JR_SalúdActionPerformed

    private void JR_LicenciaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_LicenciaturasActionPerformed
        cb_Licenciaturas.setVisible(true);
        cb_Salúd.setVisible(false);
        cb_Ingeniería.setVisible(false);
    }//GEN-LAST:event_JR_LicenciaturasActionPerformed

    private void Guardar_CarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_CarrerasActionPerformed
        Boolean f = false;
        try {
            String jefe;
            String Facultad = "";
            String Carrera = "5";
            Float costo;
            jefe = Jefe.getText();
            costo = Float.parseFloat(Costo.getText());

            if (JR_Ingeniería.isSelected()) {
                Facultad = "Ingeniería";
                if (cb_Ingeniería.getSelectedIndex() == 0) {
                    Carrera = "Ingeniería en sistemas computacionales";
                }
                if (cb_Ingeniería.getSelectedIndex() == 1) {
                    Carrera = "Ingeniería Industrial y de sistemas";
                }
                if (cb_Ingeniería.getSelectedIndex() == 2) {
                    Carrera = "Ingeniería Mecatrónica";
                }
                if (cb_Ingeniería.getSelectedIndex() == 3) {
                    Carrera = "Ingeniería Biomédica";
                }
                if (cb_Ingeniería.getSelectedIndex() == 4) {
                    Carrera = "Ingeniería en Energía";
                }
                Carrera c = new Carrera(Carrera, Facultad, costo, jefe);
                DefaultListModel modelo
                        = (DefaultListModel) JL_Carrera.getModel();
                modelo.addElement(c);
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(c);
                cb_Carreras.setModel(dc);
            }
            if (JR_Licenciaturas.isSelected()) {
                Facultad = "Licenciaturas";
                if (cb_Licenciaturas.getSelectedIndex() == 0) {
                    Carrera = "Licenciatura en Finanzas";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 1) {
                    Carrera = "Licenciatura en Derecho";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 2) {
                    Carrera = "Administración de Empresas";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 3) {
                    Carrera = "Diseño Gráfico";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 4) {
                    Carrera = "Mercadotecnia";
                }
                Carrera c = new Carrera(Carrera, Facultad, costo, jefe);

                DefaultListModel modelo
                        = (DefaultListModel) JL_Carrera.getModel();
                modelo.addElement(c);
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(c);
                cb_Carreras.setModel(dc);
            }
            if (JR_Salúd.isSelected()) {
                Facultad = "Ciencias de la salúd";
                if (cb_Salúd.getSelectedIndex() == 0) {
                    Carrera = "Medicina y Cirugía";
                }
                if (cb_Salúd.getSelectedIndex() == 1) {
                    Carrera = "Odontología";
                }
                if (cb_Salúd.getSelectedIndex() == 2) {
                    Carrera = "Nutrición";
                }
                if (cb_Salúd.getSelectedIndex() == 3) {
                    Carrera = "Terapia Física y  ocupacional";
                }
                Carrera c = new Carrera(Carrera, Facultad, costo, jefe);
                DefaultListModel modelo
                        = (DefaultListModel) JL_Carrera.getModel();
                modelo.addElement(c);
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(c);
                cb_Carreras.setModel(dc);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear la clase");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Carrera Creada exitosamente");
            jDialog1.setVisible(false);
        }
    }//GEN-LAST:event_Guardar_CarrerasActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        jDialog6.setModal(true);
        jDialog6.pack();
        jDialog6.setLocationRelativeTo(this);
        jDialog6.setVisible(true);     

    }//GEN-LAST:event_EditarActionPerformed

    private void JL_CarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_CarreraMouseClicked
        if (JL_Carrera.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Editar_Carrera.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_JL_CarreraMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (JL_Carrera.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) JL_Carrera.getModel();
            modelo.remove(JL_Carrera.getSelectedIndex());
            JL_Carrera.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void Agregar_AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_AlumnosActionPerformed
        String nombre;
        String apellido;
        int cuenta;
        int edad;
        String sexo;
        Boolean f = false;
        try {
            nombre = Nombre.getText();
            apellido = Apellido.getText();
            cuenta = Integer.parseInt(Numero_Cuenta.getText());
            edad = (Integer) SP_Edad.getValue();
            if (Botón_M.isSelected()) {
                sexo = "Hombre";
            } else {
                sexo = "Mujer";
            }
            Carrera c = (Carrera) cb_Carreras.getSelectedItem();
            Estudiantes E = new Estudiantes(nombre, apellido, cuenta, edad, sexo, c);
            Alumnos.add(E);
            DefaultListModel modelo
                    = (DefaultListModel) JL_Estudiantes.getModel();
            modelo.addElement(E);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear el Estudiante");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Estudiante Creado exitosamente");
            jDialog2.setVisible(false);
            Nombre.setText("");
            Apellido.setText("");

        }


    }//GEN-LAST:event_Agregar_AlumnosActionPerformed

    private void Botón_EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_EstudiantesActionPerformed
        jDialog2.setModal(true);
        jDialog2.pack();
        jDialog2.setLocationRelativeTo(this);
        jDialog2.setVisible(true);    }//GEN-LAST:event_Botón_EstudiantesActionPerformed

    private void JL_EstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_EstudiantesMouseClicked
        if (JL_Carrera.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Editar_Estudiante.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }

        }
    }//GEN-LAST:event_JL_EstudiantesMouseClicked

    private void Editar_EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_EstudiantesActionPerformed
        DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Estudiantes.getModel();
        ((Estudiantes) modeloLISTA.get(
                JL_Estudiantes.getSelectedIndex())).
                setNombre(JOptionPane.showInputDialog("nombre"));
        JL_Estudiantes.setModel(modeloLISTA);
    }//GEN-LAST:event_Editar_EstudiantesActionPerformed

    private void Eliminar_EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_EstudiantesActionPerformed
        if (JL_Carrera.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) JL_Estudiantes.getModel();
            modelo.remove(JL_Estudiantes.getSelectedIndex());
            JL_Estudiantes.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

        }    }//GEN-LAST:event_Eliminar_EstudiantesActionPerformed

    private void Botón_crearclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_crearclaseActionPerformed
        Boolean f = false;
        try {
            String nombre;
            String sección;
            int edificio;
            int salón;
            String Aire;
            nombre = Clase.getText();
            sección = Sección.getText();
            edificio = Integer.parseInt(Edificio.getText());
            salón = Integer.parseInt(Salón.getText());
            if (RB_Sí.isSelected()) {
                Aire = "Sí";

            } else {
                Aire = "No";
            }
            Clases c = new Clases(nombre, sección, edificio, salón, Aire);
            DefaultListModel modelo
                    = (DefaultListModel) JL_Clases.getModel();
            modelo.addElement(c);
            DefaultComboBoxModel dc
                    = (DefaultComboBoxModel) cb_clases_M.getModel();
            dc.addElement(c.getNombre());
            cb_clases_M.setModel(dc);

             DefaultComboBoxModel df
                    = (DefaultComboBoxModel) cb_clases_M1.getModel();
            df.addElement(c.getNombre());
            cb_clases_M.setModel(dc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear la Clase");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Clase Creada exitosamente");
            jDialog3.setVisible(false);
            Clase.setText("");
            Sección.setText("");
            Edificio.setText("");
            Salón.setText("");

        }


    }//GEN-LAST:event_Botón_crearclaseActionPerformed

    private void Botón_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_ClaseActionPerformed
        jDialog3.setModal(true);
        jDialog3.pack();
        jDialog3.setLocationRelativeTo(this);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_Botón_ClaseActionPerformed

    private void Editar_clase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_clase1ActionPerformed
       
        jDialog7.setModal(true);
        jDialog7.pack();
        jDialog7.setLocationRelativeTo(this);
        jDialog7.setVisible(true);
        
    }//GEN-LAST:event_Editar_clase1ActionPerformed

    private void Eliminar_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ClaseActionPerformed
        if (JL_Carrera.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) JL_Carrera.getModel();
            modelo.remove(JL_Carrera.getSelectedIndex());
            JL_Carrera.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");    }//GEN-LAST:event_Eliminar_ClaseActionPerformed

    }
    private void JL_ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_ClasesMouseClicked
        if (JL_Carrera.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Editar_Clase.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }

        }
    }//GEN-LAST:event_JL_ClasesMouseClicked

    private void Botón_MaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_MaestrosActionPerformed
        jDialog4.setModal(true);
        jDialog4.pack();
        jDialog4.setLocationRelativeTo(this);
        jDialog4.setVisible(true);
    }//GEN-LAST:event_Botón_MaestrosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Boolean f = false;
        try {
            String nombre;
            String apellido;
            Float salario;
            int edad;
            nombre = Nombre_M1.getText();
            apellido = Apellido_M.getText();
            salario = Float.parseFloat(Salario_M.getText());
            edad = Integer.parseInt(Edad_M.getText());
           // Clases c = ((Clases) cb_clases_M.getSelectedItem());
            Maestros m = new Maestros(nombre, apellido, salario, edad);
           // m.getClases().add(c);
            DefaultListModel modelo
                    = (DefaultListModel) JL_Maestros.getModel();
            modelo.addElement(m);
            DefaultComboBoxModel dz
                    = (DefaultComboBoxModel) cb_clases_M.getModel();
            dz.addElement(m);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear el maestro");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Maestro Creado exitosamente");
            jDialog4.setVisible(false);
            Nombre_M1.setText("");
            Apellido_M.setText("");
            Salario_M.setText("");
            Edad_M.setText("");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JL_MaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_MaestrosMouseClicked
        if (JL_Carrera.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Editar_Maestros.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }

        }
    }//GEN-LAST:event_JL_MaestrosMouseClicked

    private void Editar_maestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_maestroActionPerformed
        jDialog5.setModal(true);
        jDialog5.pack();
        jDialog5.setLocationRelativeTo(this);
        jDialog5.setVisible(true);
        
            
        
        
        
    }//GEN-LAST:event_Editar_maestroActionPerformed

    private void Eliminar_MaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_MaestroActionPerformed
         if (JL_Maestros.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) JL_Maestros.getModel();
            modelo.remove(JL_Maestros.getSelectedIndex());
            JL_Maestros.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");}
    }//GEN-LAST:event_Eliminar_MaestroActionPerformed

    private void Agregar_al_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_al_arbolActionPerformed
      DefaultTreeModel m =(DefaultTreeModel)jTree1.getModel();
        DefaultMutableTreeNode raiz= (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo;//creo el nodo principal
         Carrera c=Alumnos.get(0).getCarrera();
        nodo=new DefaultMutableTreeNode(c);
        DefaultMutableTreeNode name;//nodo del nombre
        String name2=Alumnos.get(0).getNombre();
        name = new DefaultMutableTreeNode(name2);//agrego el nombre al nodo


        nodo.add(name);
        raiz.add(nodo);
        m.reload();  
    }//GEN-LAST:event_Agregar_al_arbolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean f = false;
        try{
        DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Maestros.getModel();

        ((Maestros) modeloLISTA.get(
                JL_Maestros.getSelectedIndex())).
                setNombre(Nombre_M2.getText());
        ((Maestros) modeloLISTA.get(
                JL_Maestros.getSelectedIndex())).
                setApellido(Apellido_M1.getText());
        ((Maestros) modeloLISTA.get(
                JL_Maestros.getSelectedIndex())).
                setSalario(Float.parseFloat(Salario_M1.getText()));
        ((Maestros) modeloLISTA.get(
                JL_Maestros.getSelectedIndex())).
                setEdad(Integer.parseInt(Edad_M1.getText()));
        //lases c = ((Clases)cb_clases_M.getSelectedItem());
       // ((Maestros) modeloLISTA.get(
        //        JL_Maestros.getSelectedIndex())).getClases().add(c);
        JL_Maestros.setModel(modeloLISTA);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error, no se pudo guardar el archivo");
            f= true;
        } if(f==false){
            JOptionPane.showMessageDialog(null,"Editado perfectamente");
            Nombre_M2.setText("");
            Apellido_M1.setText("");
            Salario_M1.setText("");
            Edad_M1.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JR_Ingeniería1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_Ingeniería1ActionPerformed
        cb_Licenciaturas1.setVisible(false);
        cb_Salúd1.setVisible(false);
        cb_Ingeniería1.setVisible(true);
    }//GEN-LAST:event_JR_Ingeniería1ActionPerformed

    private void JR_Licenciaturas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_Licenciaturas1ActionPerformed
        cb_Licenciaturas1.setVisible(true);
        cb_Salúd1.setVisible(false);
        cb_Ingeniería1.setVisible(false);    }//GEN-LAST:event_JR_Licenciaturas1ActionPerformed

    private void JR_Salúd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_Salúd1ActionPerformed
        cb_Licenciaturas1.setVisible(false);
        cb_Salúd1.setVisible(true);
        cb_Ingeniería1.setVisible(false);
    }//GEN-LAST:event_JR_Salúd1ActionPerformed

    private void cb_Licenciaturas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_Licenciaturas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_Licenciaturas1ActionPerformed

    private void Guardar_Carreras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_Carreras1ActionPerformed
       Boolean f = false;
        try {
            String jefe;
            String Facultad = "";
            String Carrera = "5";
            Float costo;
            jefe = Jefe1.getText();
            costo = Float.parseFloat(Costo1.getText());

            if (JR_Ingeniería1.isSelected()) {
                Facultad = "Ingeniería";
                if (cb_Ingeniería1.getSelectedIndex() == 0) {
                    Carrera = "Ingeniería en sistemas computacionales";
                }
                if (cb_Ingeniería1.getSelectedIndex() == 1) {
                    Carrera = "Ingeniería Industrial y de sistemas";
                }
                if (cb_Ingeniería1.getSelectedIndex() == 2) {
                    Carrera = "Ingeniería Mecatrónica";
                }
                if (cb_Ingeniería1.getSelectedIndex() == 3) {
                    Carrera = "Ingeniería Biomédica";
                }
                if (cb_Ingeniería1.getSelectedIndex() == 4) {
                    Carrera = "Ingeniería en Energía";
                }
                 DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Carrera.getModel();

        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setNombre(Carrera);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setFacultad(Facultad);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setCosto(costo);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setJefe(jefe);
        JL_Carrera.setModel(modeloLISTA);
        
        DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(JL_Carrera.getSelectedIndex());
                cb_Carreras.setModel(dc);
                
               
            }
            if (JR_Licenciaturas.isSelected()) {
                Facultad = "Licenciaturas";
                if (cb_Licenciaturas.getSelectedIndex() == 0) {
                    Carrera = "Licenciatura en Finanzas";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 1) {
                    Carrera = "Licenciatura en Derecho";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 2) {
                    Carrera = "Administración de Empresas";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 3) {
                    Carrera = "Diseño Gráfico";
                }
                if (cb_Licenciaturas.getSelectedIndex() == 4) {
                    Carrera = "Mercadotecnia";
                }
               

                 DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Carrera.getModel();

        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setNombre(Carrera);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setFacultad(Facultad);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setCosto(costo);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setJefe(jefe);
        JL_Carrera.setModel(modeloLISTA);
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(JL_Carrera.getSelectedIndex());
                cb_Carreras.setModel(dc);
            }
            if (JR_Salúd.isSelected()) {
                Facultad = "Ciencias de la salúd";
                if (cb_Salúd.getSelectedIndex() == 0) {
                    Carrera = "Medicina y Cirugía";
                }
                if (cb_Salúd.getSelectedIndex() == 1) {
                    Carrera = "Odontología";
                }
                if (cb_Salúd.getSelectedIndex() == 2) {
                    Carrera = "Nutrición";
                }
                if (cb_Salúd.getSelectedIndex() == 3) {
                    Carrera = "Terapia Física y  ocupacional";
                }
                 DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Carrera.getModel();

        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setNombre(Carrera);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setFacultad(Facultad);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setCosto(costo);
        ((Carrera) modeloLISTA.get(
                JL_Carrera.getSelectedIndex())).
                setJefe(jefe);
        JL_Carrera.setModel(modeloLISTA);
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_Carreras.getModel();
                dc.addElement(JL_Carrera.getSelectedIndex());
                cb_Carreras.setModel(dc);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear la clase");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Carrera Creada exitosamente");
            jDialog6.setVisible(false);
        } 
    }//GEN-LAST:event_Guardar_Carreras1ActionPerformed

    private void Botón_crearclase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_crearclase1ActionPerformed
        Boolean f = false;
        try {
            String nombre;
            String sección;
            int edificio;
            int salón;
            String Aire;
            nombre = Clase1.getText();
            sección = Sección1.getText();
            edificio = Integer.parseInt(Edificio1.getText());
            salón = Integer.parseInt(Salón1.getText());
            if (RB_Sí1.isSelected()) {
                Aire = "Sí";

            } else {
                Aire = "No";
            }
             DefaultListModel modeloLISTA
                = (DefaultListModel) JL_Clases.getModel();

        ((Clases) modeloLISTA.get(
                JL_Clases.getSelectedIndex())).
                setNombre(nombre);
        ((Clases) modeloLISTA.get(
                JL_Clases.getSelectedIndex())).
                setSección(sección);
        ((Clases) modeloLISTA.get(
                JL_Clases.getSelectedIndex())).
                setEdificio(edificio);
        ((Clases) modeloLISTA.get(
                JL_Clases.getSelectedIndex())).
                setSalón(salón);
        JL_Clases.setModel(modeloLISTA);
        
                DefaultComboBoxModel dc
                        = (DefaultComboBoxModel) cb_clases_M.getModel();
                dc.addElement(JL_Clases.getSelectedIndex());
                cb_clases_M.setModel(dc);
                
          
            

             DefaultComboBoxModel df
                    = (DefaultComboBoxModel) cb_clases_M1.getModel();
            df.addElement(JL_Clases.getSelectedIndex());
            cb_clases_M.setModel(dc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error y no se pudo crear la Clase");
            f = true;
        }
        if (f == false) {
            JOptionPane.showMessageDialog(null, "Clase Creada exitosamente");
            jDialog7.setVisible(false);
            Clase1.setText("");
            Sección1.setText("");
            Edificio1.setText("");
            Salón1.setText("");

        }
    }//GEN-LAST:event_Botón_crearclase1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public void main() {
        initComponents();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Alumnos;
    private javax.swing.JMenuItem Agregar_al_arbol;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Apellido_M;
    private javax.swing.JTextField Apellido_M1;
    private javax.swing.JButton Botón_Carrera;
    private javax.swing.JButton Botón_Clase;
    private javax.swing.JButton Botón_Estudiantes;
    private javax.swing.JRadioButton Botón_F;
    private javax.swing.JRadioButton Botón_M;
    private javax.swing.JButton Botón_Maestros;
    private javax.swing.JButton Botón_crearclase;
    private javax.swing.JButton Botón_crearclase1;
    private javax.swing.JTextField Clase;
    private javax.swing.JTextField Clase1;
    private javax.swing.JTextField Costo;
    private javax.swing.JTextField Costo1;
    private javax.swing.JTextField Edad_M;
    private javax.swing.JTextField Edad_M1;
    private javax.swing.JTextField Edificio;
    private javax.swing.JTextField Edificio1;
    private javax.swing.JMenuItem Editar;
    private javax.swing.JPopupMenu Editar_Carrera;
    private javax.swing.JPopupMenu Editar_Clase;
    private javax.swing.JPopupMenu Editar_Estudiante;
    private javax.swing.JMenuItem Editar_Estudiantes;
    private javax.swing.JPopupMenu Editar_Maestros;
    private javax.swing.JMenuItem Editar_clase1;
    private javax.swing.JMenuItem Editar_maestro;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar_Clase;
    private javax.swing.JMenuItem Eliminar_Estudiantes;
    private javax.swing.JMenuItem Eliminar_Maestro;
    private javax.swing.JButton Guardar_Carreras;
    private javax.swing.JButton Guardar_Carreras1;
    private javax.swing.JList<String> JL_Carrera;
    private javax.swing.JList<String> JL_Clases;
    private javax.swing.JList<String> JL_Estudiantes;
    private javax.swing.JList<String> JL_Maestros;
    private javax.swing.JRadioButton JR_Ingeniería;
    private javax.swing.JRadioButton JR_Ingeniería1;
    private javax.swing.JRadioButton JR_Licenciaturas;
    private javax.swing.JRadioButton JR_Licenciaturas1;
    private javax.swing.JRadioButton JR_Salúd;
    private javax.swing.JRadioButton JR_Salúd1;
    private javax.swing.JTextField Jefe;
    private javax.swing.JTextField Jefe1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre_M1;
    private javax.swing.JTextField Nombre_M2;
    private javax.swing.JTextField Numero_Cuenta;
    private javax.swing.JRadioButton RB_No;
    private javax.swing.JRadioButton RB_No1;
    private javax.swing.JRadioButton RB_Sí;
    private javax.swing.JRadioButton RB_Sí1;
    private javax.swing.JSpinner SP_Edad;
    private javax.swing.JTextField Salario_M;
    private javax.swing.JTextField Salario_M1;
    private javax.swing.JTextField Salón;
    private javax.swing.JTextField Salón1;
    private javax.swing.JTextField Sección;
    private javax.swing.JTextField Sección1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb_Carreras;
    private javax.swing.JComboBox<String> cb_Ingeniería;
    private javax.swing.JComboBox<String> cb_Ingeniería1;
    private javax.swing.JComboBox<String> cb_Licenciaturas;
    private javax.swing.JComboBox<String> cb_Licenciaturas1;
    private javax.swing.JComboBox<String> cb_Salúd;
    private javax.swing.JComboBox<String> cb_Salúd1;
    private javax.swing.JComboBox<String> cb_clases_M;
    private javax.swing.JComboBox<String> cb_clases_M1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
ArrayList<Estudiantes> Alumnos = new ArrayList();
}
